#!/bin/bash
if [[ "$OSTYPE" == "darwin"* ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
SCRIPTPATH=$($READLINK -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)

cabal exec runhaskell -- \
  $SCRIPTDIR/src/Main.hs

