#!/bin/bash
if [[ "$OSTYPE" == "darwin"* ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
SCRIPTPATH=$($READLINK -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
PROJECTDIR=$(dirname $SCRIPTDIR)

pushd $PROJECTDIR
cabal exec runhaskell -- \
  $PROJECTDIR/src/Main.hs

