#!/bin/bash
if [[ "$OSTYPE" == "darwin"* ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
SCRIPTPATH=$($READLINK -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
PROJECTDIR=$(dirname $SCRIPTDIR)

pushd $PROJECTDIR &&
  stack runghc $PROJECTDIR/src/Main.hs
